# This file contains values from Cookiecutter

default_context:
  project_name: "sec_edger_harvester"
  project_description: "Python library to harvest target exhibit files list from sec edger database that matches given list of phrases"
  organization: "https://ravirajabhat.github.io/"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.8
  github_name: "Ravirajabhat"
  email: "ravirajbhat154@gmail.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "none"
